<?php
session_start();
$sesnama = $_POST["txtNama"];
$sesemail = $_POST["txtEmail"];
$sespesan = $_POST["txtPesan"];
$sesNim = $_POST["txtNim"];
$sesNamaL = $_POST["txtNamaL"];
$sesTempat = $_POST["txtTempat"];
$sesTanggal = $_POST["txtTanggal"];
$sesHobi = $_POST["txtHobi"];
$sesPasangan = $_POST["txtPasangan"];
$sesPekerjaan = $_POST["txtPekerjaan"];
$sesOrtu = $_POST["txtOrtu"];
$sesKakak = $_POST["txtKakak"];
$sesAdik = $_POST["txtAdik"];
$_SESSION["sesnama"] = $sesnama;
$_SESSION["sesemail"] = $sesemail;
$_SESSION["sespesan"] = $sespesan;
$_SESSION["sesNim"] = $sesNim;
$_SESSION["sesNamaL"] = $sesNamaL;
$_SESSION["sesTempat"] = $sesTempat;
$_SESSION["sesTanggal"] = $sesTanggal;
$_SESSION["sesHobi"] = $sesHobi;
$_SESSION["sesPasangan"] = $sesPasangan;
$_SESSION["sesPekerjaan"] = $sesPekerjaan;
$_SESSION["sesortu"] = $sesOrtu;
$_SESSION["sesKakak"] = $sesKakak;
$_SESSION["sesAdik"] = $sesAdik;
header("location: index.php");
?>